spring.datasource.url=jdbc:postgresql://localhost:5433/cashvane
spring.datasource.username=cashvane_user
spring.datasource.password=cashvane_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true